<?php

namespace Wypozyczalnia\TestBundle\Entity;

use Doctrine\ORM\EntityRepository;

/**
 * OpinionsRepository
 *
 * This class was generated by the Doctrine ORM. Add your own custom
 * repository methods below.
 */
class OpinionsRepository extends EntityRepository
{
}
